"""Generate the Aurora inline star field as absolutely-positioned <div>s.

One-shot, seeded so rebuilds don't reflow. Output is a Jinja partial
included by base.html. Each star is a tiny div with its own --bo (base
opacity), --r (radius in px), --dur (twinkle duration), --d (delay).
Hero stars carry a static box-shadow halo (cheap — not animated).
"""
import random

random.seed(42)

TINTS_SMALL = ['#e8f0ff', '#fff4e0', '#ffffff', '#ffffff', '#dfe8ff']
TINTS_MED   = ['#ffffff', '#f4e9ff', '#fff1d8', '#e0eaff']
TINTS_HERO  = ['#ffffff', '#fff6e0', '#e6efff']

def rpos():
    return round(random.uniform(0, 100), 2), round(random.uniform(0, 100), 2)

def rclock():
    return round(random.uniform(3.2, 8.5), 2), round(random.uniform(-12, 0), 2)

def small(count):
    rows = []
    for _ in range(count):
        x, y = rpos()
        dur, delay = rclock()
        op = round(random.uniform(0.45, 0.78), 2)
        fill = random.choice(TINTS_SMALL)
        rows.append(
            f'<i class="aur-star" style="left:{x}%;top:{y}%;'
            f'width:1.2px;height:1.2px;background:{fill};'
            f'--bo:{op};animation:aur-twinkle {dur}s ease-in-out {delay}s infinite"></i>'
        )
    return '\n      '.join(rows)

def med(count):
    rows = []
    for _ in range(count):
        x, y = rpos()
        dur, delay = rclock()
        op = round(random.uniform(0.70, 0.92), 2)
        fill = random.choice(TINTS_MED)
        rows.append(
            f'<i class="aur-star" style="left:{x}%;top:{y}%;'
            f'width:2px;height:2px;background:{fill};'
            f'--bo:{op};animation:aur-twinkle {dur}s ease-in-out {delay}s infinite"></i>'
        )
    return '\n      '.join(rows)

def hero(count):
    rows = []
    for _ in range(count):
        x, y = rpos()
        dur, delay = rclock()
        fill = random.choice(TINTS_HERO)
        # box-shadow halo: 0 0 <blur> <spread> color — static, no animation cost.
        rows.append(
            f'<i class="aur-star aur-star--hero" style="left:{x}%;top:{y}%;'
            f'width:3px;height:3px;background:{fill};'
            f'box-shadow:0 0 10px 1.5px {fill}66;'
            f'--bo:0.95;animation:aur-twinkle {dur}s ease-in-out {delay}s infinite"></i>'
        )
    return '\n      '.join(rows)

# Build star markup ONCE per layer, then render it twice inside each
# layer's wrapper. Two identical "lanes" stacked vertically inside a
# 200vh-tall layer let the CSS @keyframes translate the wrapper by
# -50% over a long duration with a seamless visual loop — what's at
# the top after the snap is what was at the bottom just before, pixel
# for pixel.
far_stars  = small(80) + '\n      ' + med(30)
near_stars = hero(8)

out = f'''{{#- Inline-generated star field. 126 absolutely-positioned <i> elements:
   80 small (1.2px), 30 medium (2px), 8 hero (3px + box-shadow halo).
   Two parallax-warp layers (FAR slow, NEAR fast); each layer is the
   stars rendered twice in stacked lanes so the @keyframes aur-warp
   can translate -50% infinitely without a visible snap. Each star
   carries its own --bo and random twinkle duration/delay.
   Generated by hooks/gen_stars.py (seed=42). -#}}
<div class="aur-starfield" aria-hidden="true">
  <div class="aur-starfield__dust"></div>
  <div class="aur-starfield__layer aur-starfield__layer--far">
    <div class="aur-starfield__lane">
      {far_stars}
    </div>
    <div class="aur-starfield__lane">
      {far_stars}
    </div>
  </div>
  <div class="aur-starfield__layer aur-starfield__layer--near">
    <div class="aur-starfield__lane">
      {near_stars}
    </div>
    <div class="aur-starfield__lane">
      {near_stars}
    </div>
  </div>
</div>
'''

with open("C:/Users/Sam/Desktop/Training/salesforce-training-v2/docs/overrides/_aurora-stars.html", "w", encoding="utf-8") as f:
    f.write(out)
print(f"Wrote {len(out)} chars, {out.count('aur-star')} star tags")
